# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: ['master'] # 监听 main 分支的推送

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 你可以使用更新的版本，比如 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # 打包命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 告诉 Actions 去这个文件夹里取打包好的文件
